# This template merge config file lists:
# - patterns: strings to do text substitution on
# - rev_id: a sequential revision id of the template repo (manually maintained for now)
# - required: a full list of all files always merged
# - optional: a full list of all files merged when the --optional flag is used with `gut template`
name = "Language Template"
patterns = ["__UND__", "__UND2C__", "__UNDEFINED__"]
rev_id = 1
required = ["configure.ac",
            "tools/shellscripts/u__UND__-gt.sh.in",
            "tools/shellscripts/Makefile.am",
            "tools/mt/filters/Makefile.am",
            "tools/mt/Makefile.modifications.am",
            "tools/mt/Makefile.am",
            "tools/mt/apertium/filters/Makefile.am",
            "tools/mt/apertium/Makefile.modifications.am",
            "tools/mt/apertium/Makefile.am",
            "tools/mt/apertium/tagsets/Makefile.am",
            "tools/mt/cgbased/Makefile.am",
            "tools/hyphenators/filters/Makefile.am",
            "tools/hyphenators/Makefile.am",
            "tools/hyphenators/Makefile.modification-fst.am",
            "tools/hyphenators/Makefile.modification-pattern.am",
            "tools/spellcheckers/filters/Makefile.mod-mobile-filters.am",
            "tools/spellcheckers/filters/Makefile.am",
            "tools/spellcheckers/filters/Makefile.mod-desktop-filters.am",
            "tools/spellcheckers/filters/Makefile.mod-fstbased-filters.am",
            "tools/spellcheckers/Makefile.mod-spellcheckers.am",
            "tools/spellcheckers/weights/Makefile.am",
            "tools/spellcheckers/Makefile.mod-mobile-hfst.am",
            "tools/spellcheckers/Makefile.am",
            "tools/spellcheckers/Makefile.mod-fstbased.am",
            "tools/spellcheckers/Makefile.mod-desktop.am",
            "tools/spellcheckers/Makefile.mod-mobile.am",
            "tools/spellcheckers/Makefile.mod-desktop-hfst.am",
            "tools/Makefile.am",
            "tools/tokenisers/filters/Makefile.am",
            "tools/tokenisers/Makefile.am",
            "tools/analysers/Makefile.am",
            "tools/grammarcheckers/filters/Makefile.am",
            "tools/grammarcheckers/Makefile.am",
            "test/tools/mt/Makefile.am",
            "test/tools/mt/apertium/Makefile.am",
            "test/tools/mt/apertium/run-mt-gt-desc-anayaml-testcases.sh",
            "test/tools/hyphenators/fstbased/Makefile.am",
            "test/tools/hyphenators/Makefile.am",
            "test/tools/hyphenators/patternbased/Makefile.am",
            "test/tools/spellcheckers/fstbased/run-fstspeller-gt-norm-yaml-testcases.sh",
            "test/tools/spellcheckers/fstbased/desktop/hfst/run-acceptor-yaml-testcases.sh",
            "test/tools/spellcheckers/fstbased/desktop/hfst/Makefile.am",
            "test/tools/spellcheckers/fstbased/desktop/hfst/test-zhfst-basic-sugg-speed.sh.in",
            "test/tools/spellcheckers/fstbased/desktop/hfst/accept-all-lemmas.sh.in",
            "test/tools/spellcheckers/fstbased/desktop/Makefile.am",
            "test/tools/spellcheckers/fstbased/Makefile.am",
            "test/tools/spellcheckers/fstbased/mobile/Makefile.am",
            "test/tools/spellcheckers/test-zhfst-file.sh.in",
            "test/tools/spellcheckers/Makefile.am",
            "test/tools/spellcheckers/run-spellers-gt-norm-yaml-testcases.sh",
            "test/tools/Makefile.am",
            "test/run-yaml-testcases.sh.in",
            "test/check_lemmas.sh",
            "test/error-handling-stubs.sh",
            "test/run-morph-tester.sh.in",
            "test/Makefile.am",
            "test/src/run-gt-desc-genyaml-testcases.sh",
            "test/src/orthography/Makefile.am",
            "test/src/orthography/run-initcaps-genyaml-testcases.sh",
            "test/src/phonology/pair-test-negative.sh.in",
            "test/src/phonology/Makefile.am",
            "test/src/phonology/pair-test-hfst.sh.in",
            "test/src/phonology/pair-test-positive.sh.in",
            "test/src/run-dict-gt-desc-anayaml-testcases.sh",
            "test/src/run-gt-norm-genyaml-testcases.sh",
            "test/src/Makefile.am",
            "test/src/run-gt-norm-yaml-testcases.sh",
            "test/src/run-lexc-testcases.sh",
            "test/src/run-gt-norm-anayaml-testcases.sh",
            "test/src/run-gt-desc-yaml-testcases.sh",
            "test/src/morphology/generate-noun-lemmas.sh.in",
            "test/src/morphology/tag_test.sh",
            "test/src/morphology/generate-adjective-lemmas.sh.in",
            "test/src/morphology/Makefile.am",
            "test/src/morphology/generate-verb-lemmas.sh.in",
            "test/src/morphology/generate-propernoun-lemmas.sh.in",
            "test/src/run-gt-desc-anayaml-testcases.sh",
            "test/src/syntax/Makefile.am",
            "test/src/run-dict-gt-norm-genyaml-testcases.sh",
            "giella-__UND__.pc.in",
            "Makefile.am",
            "devtools/test_voikkospell_suggestions.sh.in",
            "devtools/generate-noun-wordforms.sh",
            "devtools/generate-verb-wordforms.sh",
            "devtools/generate-adj-wordforms.sh",
            "devtools/test_ospell-office_suggestions.sh.in",
            "devtools/generate-prop-wordforms.sh",
            "devtools/test_grammar_checker.sh.in",
            "devtools/check_analysis_regressions.sh.in",
            "m4/giella-macros.m4",
            "m4/ax_compare_version.m4",
            "m4/hfst.m4",
            "m4/ax_python_module.m4",
            "m4/ax_java_modules.m4",
            "m4/ax_check_gnu_make.m4",
            "m4/giella-config-files.m4",
            "doc/Makefile.am",
            "autogen.sh",
            "src/filters/Makefile.am",
            "src/cg3/Makefile.am",
            "src/orthography/Makefile.am",
            "src/hyphenation/Makefile.am",
            "src/Makefile.am",
            "src/transcriptions/Makefile.am",
            "src/phonetics/Makefile.am",
            "src/tagsets/Makefile.am",
            "src/fst/Makefile.am",
            "src/fst/Makefile.modifications-phon.am"]

optional = ["tools/mt/apertium/tagsets/README.txt",
            "tools/spellcheckers/index.xml",
            "tools/spellcheckers/index.mobile.xml",
            "tools/spellcheckers/weights/00README.txt",
            "tools/tokenisers/tokeniser-gramcheck-gt-desc.pmscript",
            "tools/tokenisers/tokeniser-disamb-gt-desc.pmscript",
            "tools/analysers/pipespec.xml.in",
            "tools/grammarcheckers/pipespec.xml.in",
            "tools/grammarcheckers/index.xml",
            "INSTALL",
            "AUTHORS",
            "README",
            "LICENCE",
            "devtools/00README.txt",
            "src/fst/generated_files/00README.txt",
            "src/fst/incoming/00README.txt"]

ignored = []
